version: '3.5'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescale-assignment-db
    environment:
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: abc123
    volumes:
      - ./scripts/flyway/data:/flyway/data
    ports:
      - 5432:5432

  flyway:
    container_name: timescale-assignment-flyway
    image: flyway/flyway:9-alpine
    command:
      - baseline
      - migrate
    volumes:
      - ./scripts/flyway/flyway.conf:/flyway/conf/flyway.conf
      - ./scripts/flyway/sql:/flyway/sql

  app:
    container_name: timescale-assignment-app
    build: .
    env_file: .env
    environment:
      FILE_PATH: /app/query_params.csv
      DB_URL: ${DOCKER_DB_URL}
    volumes:
      - ${DOCKER_FILE_PATH}:/app/query_params.csv
