version: '3.5'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescale-assignment-db
    environment:
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: abc123
    volumes:
      - ./scripts/flyway/data:/flyway/data
    ports:
      - 5434:5432

  flyway:
    container_name: timescale-assignment-flyway
    image: flyway/flyway:9-alpine
    command:
      - baseline
      - migrate
    volumes:
      - ./scripts/flyway/flyway.conf:/flyway/conf/flyway.conf
      - ./scripts/flyway/sql:/flyway/sql
    depends_on:
      - timescaledb

  app:
    container_name: timescale-assignment-app
    build: .
    environment:
      FILE_PATH: /app/query_params.csv
      DB_URL: postgres://homework:abc123@timescaledb:5432/homework
    volumes:
      - ./test/data/query_params.csv:/app/query_params.csv
    depends_on:
      - flyway
